### ISSUE TITLE
Im still cant debug. please hellp!!

### ISSUE THREAD

**Issue by godenfreemans** [makkarpov/uCL#1]
how do i config the configurations?
what means program arg?
please give a picture about this page.

![tim 20171125215913](https://user-images.githubusercontent.com/11087671/33231192-0a354552-d22c-11e7-845b-0e5f758f8241.png)

pls 
tks

**Comment by makkarpov** [comment]
What errors does it output?

Program arguments is inherited from standard CLion run configuration, of course here it makes no sense. You need _either_ OpenOCD parameters with script or script itself, not both.

Please ensure that you have `arm-none-eabi-gdb` set as GDB executable and set path to OpenOCD.

**Comment by godenfreemans** [comment]
Ha，as you say , its worked! how about add a GDB seleter in your plugin? i see a warring in setting and i feel a little uncomfortable.
![h_ q 6p 3f8e8f wx7wr37](https://user-images.githubusercontent.com/11087671/33236809-3bdf9418-d29a-11e7-90b0-66083d770858.png)
and there is a bug.
when i check "upload firmware to the target. the DEBUG fail.
the error message here:
```
auto erase enabled
Error: couldn't open C:UsersGodenfreemansSTM32B-L475E-IOT01A    estcmake-build-d
ebug    est.elf
```
 i think maybe is path problem.

finally .thank your plugin, its really really helpfull.

**Comment by godenfreemans** [comment]
By the way, I will make a blog about your plugin,,😆
